record httprequest {
    path: string,
    headers: list<tuple<string, string>>,
    querystring: string,
    payload: string,
    method: string
}

record httpresponse{
    data: string,
    success: bool
}

handlerequest: func(a: httprequest) -> httpresponse
